site_name: Smiles Validator
theme:
  name: "material"
  palette:
    - scheme: default
      primary: deep purple
      accent: lime
    - scheme: slate
      primary: deep purple
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: true
            separate_signature: true
            show_signature_annotations: true

nav:
  - Home: index.md
  - Parser: parser.md
  - Chemistry: chem.md
  - Analyses: analyses.md
  - API Reference:
    - Validator: reference/validator.md
    - Chem: reference/chem.md